/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an audio file for analysis */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health and limits */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status and current processing stage */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full analysis result */
        get: operations["get_result_api_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /**
             * Beginner Chords
             * @description Simplified chords with consecutive duplicates merged
             */
            beginner_chords: components["schemas"]["SimpleChordSegment"][];
            /** Capo Note */
            capo_note: string;
            /** Capo Suggestions */
            capo_suggestions: components["schemas"]["CapoSuggestion"][];
            /** Chords */
            chords: components["schemas"]["ChordSegment"][];
            confidence: components["schemas"]["OverallConfidence"];
            metadata: components["schemas"]["Metadata"];
            music: components["schemas"]["MusicInfo"];
            rhythm: components["schemas"]["Rhythm"];
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Sections */
            sections: components["schemas"]["Section"][];
            view: components["schemas"]["ViewInfo"];
            /** Warnings */
            warnings: string[];
            /**
             * Waveform
             * @description Peak envelope (0..1) for drawing a waveform
             */
            waveform: number[];
        };
        /** Bar */
        Bar: {
            /** Chords */
            chords: components["schemas"]["BarChord"][];
            /** End */
            end: number;
            /**
             * Index
             * @description 1-based bar number; 0 = pickup before the first downbeat
             */
            index: number;
            /** Start */
            start: number;
        };
        /** BarChord */
        BarChord: {
            /** Beats */
            beats: number;
            /** Chord */
            chord: string;
            /** Simplified */
            simplified: string;
            /** Start */
            start: number;
        };
        /** Body_analyze_api_analyze_post */
        Body_analyze_api_analyze_post: {
            /**
             * File
             * @description MP3, WAV, M4A, AAC, FLAC or OGG
             */
            file: string;
        };
        /** CapoSuggestion */
        CapoSuggestion: {
            /** Capo */
            capo: number;
            /**
             * Play Chords
             * @description Distinct chord shapes in order of appearance
             */
            play_chords: string[];
            /**
             * Play Key
             * @description Key of the chord shapes you play with this capo
             */
            play_key: string;
            /**
             * Playability
             * @description Share of the song covered by easy open chords
             */
            playability: number;
        };
        /** ChordSegment */
        ChordSegment: {
            /**
             * Bar
             * @description Bar index the segment starts in (0 = pickup)
             */
            bar: number;
            /**
             * Beat
             * @description 1-based beat within that bar (0 = before first beat)
             */
            beat: number;
            /**
             * Chord
             * @description Detailed chord, e.g. "G/B" or "N" for no chord
             */
            chord: string;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Level
             * @enum {string}
             */
            confidence_level: "high" | "medium" | "low";
            /** End */
            end: number;
            /**
             * Simplified
             * @description Beginner-friendly triad, e.g. "G"
             */
            simplified: string;
            /** Start */
            start: number;
        };
        /** ConfidenceScore */
        ConfidenceScore: {
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "low";
            /**
             * Value
             * @description Heuristic score 0..1 (not a calibrated probability)
             */
            value: number;
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ffmpeg */
            ffmpeg: boolean;
            limits: components["schemas"]["ServiceLimits"];
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** JobCreated */
        JobCreated: {
            /**
             * Cached
             * @description True when an identical file was analysed before
             */
            cached: boolean;
            /** Job Id */
            job_id: string;
            links: components["schemas"]["JobLinks"];
            /** @description Included when the job is already complete (cache hit or ?wait=) */
            result?: components["schemas"]["AnalysisResult"] | null;
            status: components["schemas"]["JobStatus"];
        };
        /** JobLinks */
        JobLinks: {
            /** Export Markdown */
            export_markdown: string;
            /** Result */
            result: string;
            /** Status */
            status: string;
        };
        /** JobState */
        JobState: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error?: components["schemas"]["ErrorInfo"] | null;
            /** File Size */
            file_size: number;
            /** Filename */
            filename: string;
            /** Job Id */
            job_id: string;
            links: components["schemas"]["JobLinks"];
            stage: components["schemas"]["Stage"];
            /** Stage Label */
            stage_label: string;
            /** Stages */
            stages: components["schemas"]["StageInfo"][];
            status: components["schemas"]["JobStatus"];
            summary: components["schemas"]["JobSummary"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "processing" | "completed" | "failed";
        /** JobSummary */
        JobSummary: {
            /** Bpm */
            bpm: number | null;
            /** Duration */
            duration: number | null;
            /** Key */
            key: string | null;
        };
        /** KeyCandidate */
        KeyCandidate: {
            /** Key */
            key: string;
            /** Score */
            score: number;
        };
        /** Metadata */
        Metadata: {
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
            /** Analyzer Version */
            analyzer_version: string;
            /**
             * Duration
             * @description Seconds
             */
            duration: number;
            /**
             * File Size
             * @description Bytes
             */
            file_size: number;
            /** Filename */
            filename: string;
            /** Sample Rate */
            sample_rate: number;
            /**
             * Tuning Offset Cents
             * @description Detected deviation from A440, in cents
             */
            tuning_offset_cents: number;
        };
        /** MusicInfo */
        MusicInfo: {
            /** Bpm */
            bpm: number;
            /**
             * Bpm Alternatives
             * @description Plausible half/double-time readings
             */
            bpm_alternatives: number[];
            /** Bpm Confidence */
            bpm_confidence: number;
            /**
             * Bpm Confidence Level
             * @enum {string}
             */
            bpm_confidence_level: "high" | "medium" | "low";
            /**
             * Key
             * @description e.g. "G Major"
             */
            key: string;
            /** Key Alternatives */
            key_alternatives: components["schemas"]["KeyCandidate"][];
            /** Key Confidence */
            key_confidence: number;
            /**
             * Key Confidence Level
             * @enum {string}
             */
            key_confidence_level: "high" | "medium" | "low";
            /**
             * Time Signature
             * @description "4/4" or "3/4"
             */
            time_signature: string;
            /** Time Signature Confidence */
            time_signature_confidence: number;
            /**
             * Time Signature Confidence Level
             * @enum {string}
             */
            time_signature_confidence_level: "high" | "medium" | "low";
        };
        /** OverallConfidence */
        OverallConfidence: {
            /** @description Duration-weighted mean over detected chords */
            chords: components["schemas"]["ConfidenceScore"];
            key: components["schemas"]["ConfidenceScore"];
            structure: components["schemas"]["ConfidenceScore"];
            tempo: components["schemas"]["ConfidenceScore"];
            time_signature: components["schemas"]["ConfidenceScore"];
        };
        /** Rhythm */
        Rhythm: {
            /**
             * Beats
             * @description Beat times in seconds
             */
            beats: number[];
            /**
             * Downbeats
             * @description Bar start times in seconds
             */
            downbeats: number[];
        };
        /** Section */
        Section: {
            /** Bar End */
            bar_end: number;
            /** Bar Start */
            bar_start: number;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Level
             * @enum {string}
             */
            confidence_level: "high" | "medium" | "low";
            /** End */
            end: number;
            /** Id */
            id: string;
            /**
             * Label
             * @description Repetition label: "A", "B", ... (same label = similar music)
             */
            label: string;
            /**
             * Name
             * @description Display name, e.g. "Section A", or "Chorus" when inferred
             */
            name: string;
            /** Name Confidence */
            name_confidence: number;
            /**
             * Name Is Inferred
             * @description True when name comes from heuristics, not audio
             */
            name_is_inferred: boolean;
            /** Start */
            start: number;
        };
        /** ServiceLimits */
        ServiceLimits: {
            /** Allowed Extensions */
            allowed_extensions: string[];
            /** Max Duration Seconds */
            max_duration_seconds: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /** Min Duration Seconds */
            min_duration_seconds: number;
        };
        /** SimpleChordSegment */
        SimpleChordSegment: {
            /** Chord */
            chord: string;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Level
             * @enum {string}
             */
            confidence_level: "high" | "medium" | "low";
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /**
         * Stage
         * @description Processing stages in execution order. Progress is reported per stage, not %.
         * @enum {string}
         */
        Stage: "queued" | "converting" | "harmonic_features" | "tempo" | "key" | "chords" | "structure" | "finalizing" | "complete" | "failed";
        /** StageInfo */
        StageInfo: {
            id: components["schemas"]["Stage"];
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "done" | "active" | "pending" | "failed";
        };
        /** ViewInfo */
        ViewInfo: {
            /**
             * Chord Mode
             * @default original
             * @enum {string}
             */
            chord_mode: "original" | "beginner";
            /** Original Key */
            original_key: string;
            /**
             * Semitones
             * @description Transposition applied to this view
             */
            semitones: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_post: {
        parameters: {
            query?: {
                /** @description Seconds to wait for completion; if it finishes in time the full result is included (handy for n8n / single-request integrations). */
                wait?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_result_api_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
