"""Helpers shared by exporters."""

from __future__ import annotations

from app.exporters.chord_sheet import ChordSheet

DISCLAIMER = (
    "Generated by Chord Analyzer. Chords are detected automatically and may contain errors."
)


def format_time(seconds: float) -> str:
    total = max(0, int(seconds))
    return f"{total // 60}:{total % 60:02d}"


def header_line(sheet: ChordSheet) -> str:
    return f"Key: {sheet.key} | Tempo: {round(sheet.bpm)} BPM | Time: {sheet.time_signature}"
